name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  Deploy_to_EC2:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull godcandidate/system-monitor-webapp:latest
    - name: Delete Old docker container
      run: sudo docker rm -f system-monitor-webapp-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8080:8080 --name system-monitor-webapp-container godcandidate/system-monitor-webappcle